os: linux
dist: trusty
sudo: required
services: docker
language: generic
matrix:
  include:
    - env: swift=latest
    - env: swift=4
    - env: swift=3.1
install:
  - docker pull swift:$swift;
script:
  - docker run -v $(pwd):/package -w /package swift:$swift /bin/sh -c "swift test"
